on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  quality_check:
    name: "quality_check"
    runs-on: "ubuntu-latest"
    steps:
    - name: "Get_repo"
      uses: actions/checkout@v6
    - name: "Install python"
      uses: actions/setup-python@v6
    - name: "Install libraries"
      run: pip install -r requirements.txt
    - name: "Run pytest"
      run: pytest test_main.py

    
