on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  example:
    name: "Example job"
    runs-on: "ubuntu-latest"
    steps:
     - name: "Step 1"
       run: echo "hi"
     - name: "Step 2"
       run: echo "hi"
    
